name: tester_smart
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.4
  firebase_storage: ^11.2.7
  firebase_core: ^2.27.0
  firebase_auth: ^4.0.0
  cloud_firestore: ^4.0.0
  intl: ^0.18.1 
  pdf: ^3.10.4
  printing: ^5.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png