// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi4c9dGH5oW6MluNaDTs1AsnleRoH9fRE',
    appId: '1:59094408586:web:c463056e016ffe39a27c73',
    messagingSenderId: '59094408586',
    projectId: 'smartacess-bce65',
    authDomain: 'smartacess-bce65.firebaseapp.com',
    storageBucket: 'smartacess-bce65.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1M2qn0r5nI8ViDuqj2uLglSsyp32Hf0I',
    appId: '1:59094408586:android:f6a05b16cdc0ede6a27c73',
    messagingSenderId: '59094408586',
    projectId: 'smartacess-bce65',
    storageBucket: 'smartacess-bce65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkRbdb_eqpJo6-UjRb_W4zHDHgLfTtec8',
    appId: '1:59094408586:ios:ef141ab1cd40f3fca27c73',
    messagingSenderId: '59094408586',
    projectId: 'smartacess-bce65',
    storageBucket: 'smartacess-bce65.firebasestorage.app',
    iosBundleId: 'com.example.testerSmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkRbdb_eqpJo6-UjRb_W4zHDHgLfTtec8',
    appId: '1:59094408586:ios:ef141ab1cd40f3fca27c73',
    messagingSenderId: '59094408586',
    projectId: 'smartacess-bce65',
    storageBucket: 'smartacess-bce65.firebasestorage.app',
    iosBundleId: 'com.example.testerSmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCi4c9dGH5oW6MluNaDTs1AsnleRoH9fRE',
    appId: '1:59094408586:web:85ca77df7d5fe30ea27c73',
    messagingSenderId: '59094408586',
    projectId: 'smartacess-bce65',
    authDomain: 'smartacess-bce65.firebaseapp.com',
    storageBucket: 'smartacess-bce65.firebasestorage.app',
  );
}
